### ISSUE TITLE
Add support for juju 3.x

### ISSUE THREAD

**Issue by rmalz-c** [canonical/stsstack-bundles#136]
Couple of scripts are utilizing unsupported in juju 3.x commands like juju run-action.
Running it with juju3.x will result in errors.

Some details about commands affected:
https://bugs.launchpad.net/juju/+bug/1994006

Example:
ubuntu@rmalz-bastion:~/stsstack-bundles/openstack$ ./configure
(...)
++ echo -n 'INFO: installing certificate authority for this deployment...'
INFO: installing certificate authority for this deployment...++ /home/ubuntu/stsstack-bundles/openstack/tools/install_local_ca.sh
Fetching CA cert from vault
ERROR juju: "run-action" is not a juju command. See "juju --help".

**Comment by dosaboy** [comment]
For the record stsstack-bundles has never been tested to support > 2.9. We absolutely plan to support higher versions and will start implementing that asap.

**Comment by nicolasbock** [comment]
Yes, true. @dosaboy This is a bigger story and is probably not well tracked in a single GitHub issue. Should I open a Jira ticket for it so we can track progress there?
