### ISSUE TITLE
Tutorial for modules

### ISSUE THREAD

**Issue by samuelallan72** [canonical/stsstack-bundles#178]
It's pretty straightforward to use the generate-bundle.sh tool and get it deployed on a juju model, but it's unclear what is required for post install steps.  A tutorial and/or improved docs would be great. :)

**Comment by nicolasbock** [comment]
The `generate-bundles.sh` script will list those post install steps when you run it, e.g. by adding the `--run` option of running it later manually.

**Comment by nicolasbock** [comment]
Those are options you shouldn't have to touch as a regular user. They should be fine with defaults. We set them here mainly so that we can use one main script across, e.g. openstack and kubernetes.
