### ISSUE TITLE
Not able to deploy the generated bundle

### ISSUE THREAD

**Issue by eleblebici** [canonical/stsstack-bundles#181]
For an openstack model, when I run the generate-bundle.sh script it creates the openstack.yaml file with the relations to other applications. But when I try to deploy the bundle it is giving an error like that:

```
ubuntu@bastion2:~/stsstack-bundles/openstack$ juju deploy --overlay ./b/o/glance.yaml --overlay ./b/o/keystone.yaml --overlay ./b/o/neutron-gateway.yaml --overlay ./b/o/neutron-openvswitch.yaml --overlay ./b/o/designate-ha.yaml --overlay ./b/o/neutron-ml2dns.yaml --overlay ./b/o/neutron-ml2dns-gateway.yaml --overlay ./b/o/neutron-ml2dns-openvswitch.yaml --overlay ./b/o/mysql-innodb-cluster.yaml --overlay ./b/o/mysql-innodb-cluster-router.yaml --overlay ./b/o/placement.yaml --overlay ./b/o/memcached.yaml --overlay ./b/o/designate.yaml ./b/openstack.yaml --trust
ERROR cannot deploy bundle: the provided bundle has the following errors:
relation ["nova-cloud-controller" "glance"] refers to application "glance" not defined in this bundle
relation ["nova-cloud-controller" "keystone"] refers to application "keystone" not defined in this bundle
relation ["nova-compute" "glance"] refers to application "glance" not defined in this bundle
relation ["glance" "cinder:image-service"] refers to application "glance" not defined in this bundle
relation ["glance" "rabbitmq-server"] refers to application "glance" not defined in this bundle
relation ["cinder:shared-db" "cinder-mysql-router:shared-db"] refers to application "cinder-mysql-router" not defined in this bundle
relation ["cinder:identity-service" "keystone"] refers to application "keystone" not defined in this bundle
relation ["neutron-api:shared-db" "neutron-api-mysql-router:shared-db"] refers to application "neutron-api-mysql-router" not defined in this bundle
relation ["neutron-api" "keystone"] refers to application "keystone" not defined in this bundle
```

I think it is because of [that](https://bugs.launchpad.net/juju/+bug/2041785). The bug record status is "Won't Fix". If it will be not fixed in Juju, then I think we need to fix that here.

After I moved the relations to the overlay files, I was able to deploy the bundle.

The juju version I'm using is:

```
$ juju version
3.4.2-genericlinux-amd64
```

**Comment by dosaboy** [comment]
This might be a juju 3.4 incompatibility, need to check, I know that it works fine with 3.3.

**Comment by nicolasbock** [comment]
I cannot reproduce this problem:

```console
~/stsstack-bundles/openstack $ juju version
3.4.2-genericlinux-amd64
~/stsstack-bundles/openstack $ ./generate-bundle.sh --name issue181 --run
...
Deploy of bundle completed.                                                                                                                                                                   
```

What arguments id you give the script?

**Comment by eleblebici** [comment]
> I cannot reproduce this problem:
> 
> ```
> ~/stsstack-bundles/openstack $ juju version
> 3.4.2-genericlinux-amd64
> ~/stsstack-bundles/openstack $ ./generate-bundle.sh --name issue181 --run
> ...
> Deploy of bundle completed.                                                                                                                                                                   
> ```
> 
> What arguments id you give the script?

I run the following to generate the bundle:

`./generate-bundle.sh --designate-ha --series jammy --release yoga --num-compute 1 --run`

**Comment by nicolasbock** [comment]
I still cannot reproduce. I am using commit `d219c9ee1f96b137cffc2a0d78fc50b2347c7be5`. Please make sure your `stsstack-bundles` repository is at the latest commit.

**Comment by eleblebici** [comment]
> I still cannot reproduce. I am using commit `d219c9ee1f96b137cffc2a0d78fc50b2347c7be5`. Please make sure your `stsstack-bundles` repository is at the latest commit.

@nicolasbock I was using the commit 257f540ad0bf3382d5a6b7e3765fa97c14ec1d8a and pulled the latest one. It seems this last commit has not the issue. Thank you for your help!

**Comment by nicolasbock** [comment]
I'm glad it is fixed 😄
