### ISSUE TITLE
Cannot deploy application "grafana": unknown option "admin_password"

### ISSUE THREAD

**Issue by marino-mrc** [canonical/stsstack-bundles#30]
Hi, I'm trying to deploy Openstack adding the lma overlay. Here is the output of the command:

`
~/stsstack-bundles/openstack$ ./generate-bundle.sh  --lma -s focal -r ussuri -n openstack --run
Creating Juju model openstack
Added 'openstack' model on stsstack/stsstack with credential 'marino-mrc' for user 'admin'

Created focal-ussuri bundle and overlays:
  + glance.yaml
  + keystone.yaml
  + neutron-gateway.yaml
  + neutron-openvswitch.yaml
  + neutron-ml2dns.yaml
  + neutron-ml2dns-gateway.yaml
  + neutron-ml2dns-openvswitch.yaml
  + mysql-innodb-cluster.yaml
  + mysql-innodb-cluster-router.yaml
  + placement.yaml
  + graylog.yaml
  + grafana.yaml
  + prometheus-openstack.yaml
  + prometheus-openstack-neutron-gateway.yaml

Command to deploy:
juju deploy ./b/openstack/openstack.yaml --overlay ./b/openstack/o/glance.yaml --overlay ./b/openstack/o/keystone.yaml --overlay ./b/openstack/o/neutron-gateway.yaml --overlay ./b/openstack/o/neutron-openvswitch.yaml --overlay ./b/openstack/o/neutron-ml2dns.yaml --overlay ./b/openstack/o/neutron-ml2dns-gateway.yaml --overlay ./b/openstack/o/neutron-ml2dns-openvswitch.yaml --overlay ./b/openstack/o/mysql-innodb-cluster.yaml --overlay ./b/openstack/o/mysql-innodb-cluster-router.yaml --overlay ./b/openstack/o/placement.yaml --overlay ./b/openstack/o/graylog.yaml --overlay ./b/openstack/o/grafana.yaml --overlay ./b/openstack/o/prometheus-openstack.yaml --overlay ./b/openstack/o/prometheus-openstack-neutron-gateway.yaml 
 
Located charm "cinder" in charm-hub, channel ussuri/edge
Located charm "mysql-router" in charm-hub, channel 8.0.19/edge
Located charm "elasticsearch" in charm-hub, channel stable
Located charm "filebeat" in charm-hub, channel stable
Located charm "glance" in charm-hub, channel ussuri/edge
Located charm "mysql-router" in charm-hub, channel 8.0.19/edge
Located charm "charmed-osm-grafana" in charm-hub, channel stable
Located charm "graylog" in charm-hub, channel stable
Located charm "keystone" in charm-hub, channel ussuri/edge
Located charm "mysql-router" in charm-hub, channel 8.0.19/edge
Located charm "mongodb" in charm-hub, channel stable
Located charm "mysql-innodb-cluster" in charm-hub, channel 8.0.19/edge
Located charm "neutron-api" in charm-hub, channel ussuri/edge
Located charm "mysql-router" in charm-hub, channel 8.0.19/edge
Located charm "neutron-gateway" in charm-hub, channel ussuri/edge
Located charm "neutron-openvswitch" in charm-hub, channel ussuri/edge
Located charm "nova-cloud-controller" in charm-hub, channel ussuri/edge
Located charm "mysql-router" in charm-hub, channel 8.0.19/edge
Located charm "nova-compute" in charm-hub, channel ussuri/edge
Located charm "placement" in charm-hub, channel ussuri/edge
Located charm "mysql-router" in charm-hub, channel 8.0.19/edge
Located charm "prometheus2" in charm-hub, channel stable
Located charm "prometheus-openstack-exporter" in charm-hub, channel stable
Located charm "rabbitmq-server" in charm-hub, channel 3.8/edge
Located charm "telegraf" in charm-hub, channel stable
Executing changes:
- upload charm cinder from charm-hub for series focal from channel ussuri/edge with architecture=amd64
- deploy application cinder from charm-hub on focal with ussuri/edge
  added resource policyd-override
- upload charm mysql-router from charm-hub for series focal from channel 8.0.19/edge with architecture=amd64
- deploy application cinder-mysql-router from charm-hub on focal with 8.0.19/edge using mysql-router
- upload charm elasticsearch from charm-hub for series focal from channel latest/stable with architecture=amd64
- deploy application elasticsearch from charm-hub on focal with latest/stable
- upload charm filebeat from charm-hub for series focal from channel latest/stable with architecture=amd64
- deploy application filebeat from charm-hub on focal with latest/stable
- upload charm glance from charm-hub for series focal from channel ussuri/edge with architecture=amd64
- deploy application glance from charm-hub on focal with ussuri/edge
  added resource policyd-override
- deploy application glance-mysql-router from charm-hub on focal with 8.0.19/edge using mysql-router
- upload charm charmed-osm-grafana from charm-hub for series focal from channel latest/stable with architecture=amd64
- deploy application grafana from charm-hub on focal with latest/stable using charmed-osm-grafana
ERROR cannot deploy bundle: cannot deploy application "grafana": unknown option "admin_password"
`

Removing the 'admin_password' from b/openstack/grafana.yaml causes the same error but with a different parameter:

ERROR cannot deploy bundle: cannot deploy application "grafana": unknown option "snap_channel"

or 
ERROR cannot deploy bundle: cannot deploy application "grafana": unknown option "install_method"

Regards,
Marco

**Comment by hemanthnakkina** [comment]
Operator based charm is getting downloaded -
Located charm "charmed-osm-grafana" in charm-hub, channel stable

stsstack-bundles has grafana added as part of OSM_CHARMS [1] and so pointing to operator based charm ch:charmed-osm-grafana.
LMA charms should be supported both reactive as well as operator based charms in stsstack-bundles

[1] https://github.com/canonical/stsstack-bundles/blob/master/common/charm_lists#L75
