### ISSUE TITLE
Rename master branch to main 

### ISSUE THREAD

**Issue by casual-lemon** [canonical/stsstack-bundles#33]
As part of the inclusive naming directive, we should rename the branch. I have it setup in my local fork but unable to make a PR here. https://github.com/casual-lemon/stsstack-bundles

**Comment by nicolasbock** [comment]
Thanks for bringing this up @casual-lemon

**Comment by casual-lemon** [comment]
Thanks @nicolasbock !

**Comment by nicolasbock** [comment]
We will also have to change how we create bastions on STSStack. Let me look into this first so we don't have a create new bastion outage once we make this update :)

**Comment by casual-lemon** [comment]
haha no worries

**Comment by nicolasbock** [comment]
Done :)
